# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alen Hrga
email: ahrga93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about blockchain technology and it's uses
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alenhrga.github.io" # the base hostname & protocol for your site
twitter_username: alen_hrga
github_username:  alenhrga

# Build settings
markdown: kramdown
